server:
  port: 8087
  
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3408/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8088/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
