name: microservices
services:
  accounts:
    image: "ridhorezi1212/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ridhorezi1212
  loans:
    image: "ridhorezi1212/loans:s4"
    container_name: loans-ms
    ports:
      - "8087:8087"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ridhorezi1212
  cards:
    image: "ridhorezi1212/cards:s4"
    container_name: cards-ms
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ridhorezi1212
networks:
  ridhorezi1212:
    driver: "bridge"