global:
  postgresql:
    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak

auth:
  adminUser: admin
  adminPassword: admin

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bn_keycloak
    database: bitnami_keycloak

service:
  type: LoadBalancer
  ports:
    http: 7080

extraEnvVars:
  - name: KC_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

startupProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 30
